# Generated by Django 6.0.4 on 2026-05-08 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_branchitem_collection_collectionitem_useritem'),
        ('organizations', '0014_organizationbranch_organizationbranchimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_groups', to='collections.collection')),
                ('created_by_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_donor_groups', to='organizations.organizationmember')),
            ],
            options={
                'verbose_name': 'Donor group',
                'verbose_name_plural': 'Donor groups',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DonorGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collections.donorgroup')),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_group_items', to='collections.useritem')),
            ],
            options={
                'verbose_name': 'Donor group item',
                'verbose_name_plural': 'Donor group items',
                'ordering': ('donor_group', 'user_item', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DonorGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member')], default='member', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('donor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='collections.donorgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor group member',
                'verbose_name_plural': 'Donor group members',
                'ordering': ('donor_group', 'joined_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('donor_group', 'user'), name='unique_donor_group_member')],
            },
        ),
    ]
