# Generated by Django 6.0.4 on 2026-05-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0005_courierprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorgroupmember',
            name='role',
        ),
    ]
