# Generated by Django 6.0.4 on 2026-05-09 07:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0007_meetingplaceproposal_poll_polloption_pollvote'),
        ('common', '0004_remove_city_geoname_id_remove_region_geoname_id'),
        ('organizations', '0014_organizationbranch_organizationbranchimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorGroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='collections.donorgroup')),
                ('finalized_by_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_donor_group_meetings', to='organizations.organizationmember')),
                ('geodata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_group_meetings', to='common.geodata')),
            ],
            options={
                'verbose_name': 'Donor group meeting',
                'verbose_name_plural': 'Donor group meetings',
                'ordering': ('-finalized_at', '-id'),
            },
        ),
    ]
