# Generated by Django 6.0.4 on 2026-05-09 13:59

import apps.collections.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0009_remove_courierprofile_state'),
        ('organizations', '0014_organizationbranch_organizationbranchimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='finalized_by_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_polls', to='organizations.organizationmember'),
        ),
        migrations.AddField(
            model_name='poll',
            name='finalized_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_polls', to='collections.polloption'),
        ),
        migrations.AlterField(
            model_name='donorgroupmeeting',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DonorGroupVideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to=apps.collections.models.donor_group_video_report_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reports', to='collections.donorgroup')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_group_video_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor group video report',
                'verbose_name_plural': 'Donor group video reports',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
