# Generated by Django 6.0.4 on 2026-05-09 14:58

import apps.collections.models
import apps.common.file_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0011_rename_donor_group_meeting_to_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorgroupvideoreport',
            name='video',
            field=models.FileField(upload_to=apps.collections.models.donor_group_video_report_upload_to, validators=[django.core.validators.FileExtensionValidator(('mp4', 'mov', 'webm')), apps.common.file_validators.FileContentTypeValidator(('video/mp4', 'video/quicktime', 'video/webm')), apps.common.file_validators.FileSizeValidator(524288000)]),
        ),
    ]
