# Generated by Django 6.0.4 on 2026-05-11 13:04

import apps.collections.models
import apps.common.file_validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0012_alter_donorgroupvideoreport_video'),
        ('organizations', '0016_alter_event_image_alter_eventimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorgroup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorgroup',
            name='completed_by_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_donor_group_deliveries', to='organizations.organizationmember'),
        ),
        migrations.AddField(
            model_name='donorgroup',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorgroup',
            name='hidden_by_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_donor_groups', to='organizations.organizationmember'),
        ),
        migrations.AddField(
            model_name='donorgroup',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorgroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('delivery_completed', 'Delivery completed')], default='active', max_length=30),
        ),
        migrations.CreateModel(
            name='UserItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.collections.models.user_item_image_upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif')), apps.common.file_validators.FileContentTypeValidator(('image/jpeg', 'image/png', 'image/webp', 'image/gif')), apps.common.file_validators.FileSizeValidator(5242880)])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collections.useritem')),
            ],
            options={
                'verbose_name': 'User item image',
                'verbose_name_plural': 'User item images',
                'ordering': ('user_item', 'sort_order', 'id'),
            },
        ),
    ]
