# Generated by Django 6.0.4 on 2026-05-05 13:05

from django.db import migrations, models


def copy_courier_role_to_user_field(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(user_roles__role__code="courier").update(is_courier=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            copy_courier_role_to_user_field,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
