# Generated by Django 6.0.4 on 2026-05-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_roles_remove_userrole_unique_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_courier',
        ),
    ]
