# Generated by Django 6.0.4 on 2026-05-09 14:58

import apps.common.file_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_courierprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif')), apps.common.file_validators.FileContentTypeValidator(('image/jpeg', 'image/png', 'image/webp', 'image/gif')), apps.common.file_validators.FileSizeValidator(5242880)]),
        ),
    ]
