# Generated by Django 6.0.4 on 2026-05-09 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0008_donorgroupmeeting'),
        ('communications', '0002_userdevice_notificationdelivery_and_more'),
        ('organizations', '0014_organizationbranch_organizationbranchimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_group_messages', to=settings.AUTH_USER_MODEL)),
                ('donor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collections.donorgroup')),
            ],
            options={
                'db_table': 'donor_group_messages',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_messages', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='organizations.organization')),
            ],
            options={
                'db_table': 'organization_messages',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
