# Generated by Django 6.0.4 on 2026-05-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_region_city_region_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='geoname_id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='geoname_id',
        ),
    ]
