# Generated by Django 6.0.4 on 2026-05-06 04:05

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_fix_category_verbose_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='charter_document',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='egrul_extract',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='executive_passport_copy',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='founders_appointment_decision',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='inn_certificate',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='nko_registry_notice',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='state_registration_certificate',
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='charter_document',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, verbose_name='Устав'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='egrul_extract',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, verbose_name='Выписка из ЕГРЮЛ'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='executive_passport_copy',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, verbose_name='Копия паспорта лица, осуществляющего функции единоличного исполнительного органа'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='founders_appointment_decision',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, verbose_name='Решение учредителей о назначении высшего коллегиального и исполнительного органа'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='inn_certificate',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, verbose_name='Свидетельство о присвоении ИНН'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='nko_registry_notice',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, verbose_name='Уведомление о включении в реестр НКО / Письмо-подтверждение о не включении'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='state_registration_certificate',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, verbose_name='Свидетельство о гос регистрации ЮЛ / Свидетельство о регистрации НКО'),
        ),
    ]
