# Generated by Django 6.0.4 on 2026-05-06 04:11

import apps.organizations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_organization_charter_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.organizations.models.event_image_upload_to, verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Альтернативный текст')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='organizations.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Изображение мероприятия',
                'verbose_name_plural': 'Изображения мероприятий',
                'db_table': 'event_images',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
