# Generated by Django 6.0.4 on 2026-05-06 04:32

import apps.organizations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to=apps.organizations.models.event_news_image_upload_to, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_event_news', to='organizations.organizationmember', verbose_name='Создатель')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='organizations.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Новость мероприятия',
                'verbose_name_plural': 'Новости мероприятий',
                'db_table': 'event_news',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
