# Generated by Django 6.0.4 on 2026-05-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_eventnews'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_scope',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_slug_per_scope',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizations.category', verbose_name='Категория'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='scope',
        ),
    ]
