# Generated by Django 6.0.4 on 2026-05-07 12:40

import apps.organizations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_event_news_organization(apps, schema_editor):
    organization_news_model = apps.get_model("organizations", "OrganizationNews")

    for news in organization_news_model.objects.select_related("event").all():
        news.organization_id = news.event.organization_id
        news.save(update_fields=("organization",))


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_remove_category_unique_category_name_per_scope_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_url",
            field=models.URLField(blank=True, verbose_name="MAX post"),
        ),
        migrations.AddField(
            model_name="event",
            name="vk_url",
            field=models.URLField(blank=True, verbose_name="VK post"),
        ),
        migrations.AddField(
            model_name="event",
            name="website_url",
            field=models.URLField(blank=True, verbose_name="Website event page"),
        ),
        migrations.AddField(
            model_name="organization",
            name="max_url",
            field=models.URLField(blank=True, verbose_name="MAX"),
        ),
        migrations.AddField(
            model_name="organization",
            name="vk_url",
            field=models.URLField(blank=True, verbose_name="VK"),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_url",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
        migrations.AddField(
            model_name="organizationregistrationrequest",
            name="max_url",
            field=models.URLField(blank=True, verbose_name="MAX"),
        ),
        migrations.AddField(
            model_name="organizationregistrationrequest",
            name="vk_url",
            field=models.URLField(blank=True, verbose_name="VK"),
        ),
        migrations.AddField(
            model_name="organizationregistrationrequest",
            name="website_url",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
        migrations.RenameModel(
            old_name="EventNews",
            new_name="OrganizationNews",
        ),
        migrations.AlterModelTable(
            name="organizationnews",
            table="organization_news",
        ),
        migrations.AlterModelOptions(
            name="organizationnews",
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "Новость организации",
                "verbose_name_plural": "Новости организаций",
            },
        ),
        migrations.AddField(
            model_name="organizationnews",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Комментарии"),
        ),
        migrations.AddField(
            model_name="organizationnews",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AddField(
            model_name="organizationnews",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="organizations.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.RunPython(copy_event_news_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="organizationnews",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="organizations.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnews",
            name="created_by_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_organization_news",
                to="organizations.organizationmember",
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnews",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.organizations.models.organization_news_image_upload_to,
                verbose_name="Изображение",
            ),
        ),
        migrations.RemoveField(
            model_name="organizationnews",
            name="event",
        ),
        migrations.CreateModel(
            name="OrganizationNewsComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_news_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_items",
                        to="organizations.organizationnews",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к новости",
                "verbose_name_plural": "Комментарии к новостям",
                "db_table": "organization_news_comments",
                "ordering": ("created_at", "id"),
            },
        ),
    ]
