# Generated by Django 6.0.4 on 2026-05-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('organizations', '0010_event_max_url_event_vk_url_event_website_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geodata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='common.geodata'),
        ),
    ]
