# Generated by Django 6.0.4 on 2026-05-08 07:04

import apps.organizations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_organizationmember_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.organizations.models.organization_news_gallery_image_upload_to, verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Альтернативный текст')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='organizations.organizationnews', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение новости организации',
                'verbose_name_plural': 'Изображения новостей организаций',
                'db_table': 'organization_news_images',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
