# Generated by Django 6.0.4 on 2026-05-08 07:35

import apps.organizations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_region_city_region_fk'),
        ('organizations', '0013_organizationnewsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.TextField(blank=True, verbose_name='Working hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('geodata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_branches', to='common.geodata')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization branch',
                'verbose_name_plural': 'Organization branches',
                'db_table': 'organization_branches',
                'ordering': ('organization__official_name', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationBranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.organizations.models.organization_branch_image_upload_to, verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alternative text')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='organizations.organizationbranch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Organization branch image',
                'verbose_name_plural': 'Organization branch images',
                'db_table': 'organization_branch_images',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
