# Generated by Django 6.0.4 on 2026-05-09 13:59

import apps.organizations.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_organizationbranch_organizationbranchimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(upload_to=apps.organizations.models.organization_report_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_documents', to='organizations.organizationmember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_documents', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization report document',
                'verbose_name_plural': 'Organization report documents',
                'db_table': 'organization_report_documents',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
