# Generated by Django 6.0.4 on 2026-05-09 14:58

import apps.common.file_validators
import apps.organizations.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_organizationreportdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif')), apps.common.file_validators.FileContentTypeValidator(('image/jpeg', 'image/png', 'image/webp', 'image/gif')), apps.common.file_validators.FileSizeValidator(5242880)], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=apps.organizations.models.event_image_upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif')), apps.common.file_validators.FileContentTypeValidator(('image/jpeg', 'image/png', 'image/webp', 'image/gif')), apps.common.file_validators.FileSizeValidator(5242880)], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='organizationbranchimage',
            name='image',
            field=models.ImageField(upload_to=apps.organizations.models.organization_branch_image_upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif')), apps.common.file_validators.FileContentTypeValidator(('image/jpeg', 'image/png', 'image/webp', 'image/gif')), apps.common.file_validators.FileSizeValidator(5242880)], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='organizationnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizations.models.organization_news_image_upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif')), apps.common.file_validators.FileContentTypeValidator(('image/jpeg', 'image/png', 'image/webp', 'image/gif')), apps.common.file_validators.FileSizeValidator(5242880)], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='organizationnewsimage',
            name='image',
            field=models.ImageField(upload_to=apps.organizations.models.organization_news_gallery_image_upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif')), apps.common.file_validators.FileContentTypeValidator(('image/jpeg', 'image/png', 'image/webp', 'image/gif')), apps.common.file_validators.FileSizeValidator(5242880)], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='charter_document',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.common.file_validators.FileContentTypeValidator(('application/pdf',)), apps.common.file_validators.FileSizeValidator(26214400), apps.common.file_validators.FileSignatureValidator(b'%PDF', 'Uploaded file must be a valid PDF document.')], verbose_name='Устав'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='egrul_extract',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.common.file_validators.FileContentTypeValidator(('application/pdf',)), apps.common.file_validators.FileSizeValidator(26214400), apps.common.file_validators.FileSignatureValidator(b'%PDF', 'Uploaded file must be a valid PDF document.')], verbose_name='Выписка из ЕГРЮЛ'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='executive_passport_copy',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.common.file_validators.FileContentTypeValidator(('application/pdf',)), apps.common.file_validators.FileSizeValidator(26214400), apps.common.file_validators.FileSignatureValidator(b'%PDF', 'Uploaded file must be a valid PDF document.')], verbose_name='Копия паспорта лица, осуществляющего функции единоличного исполнительного органа'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='founders_appointment_decision',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.common.file_validators.FileContentTypeValidator(('application/pdf',)), apps.common.file_validators.FileSizeValidator(26214400), apps.common.file_validators.FileSignatureValidator(b'%PDF', 'Uploaded file must be a valid PDF document.')], verbose_name='Решение учредителей о назначении высшего коллегиального и исполнительного органа'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='inn_certificate',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.common.file_validators.FileContentTypeValidator(('application/pdf',)), apps.common.file_validators.FileSizeValidator(26214400), apps.common.file_validators.FileSignatureValidator(b'%PDF', 'Uploaded file must be a valid PDF document.')], verbose_name='Свидетельство о присвоении ИНН'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='nko_registry_notice',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.common.file_validators.FileContentTypeValidator(('application/pdf',)), apps.common.file_validators.FileSizeValidator(26214400), apps.common.file_validators.FileSignatureValidator(b'%PDF', 'Uploaded file must be a valid PDF document.')], verbose_name='Уведомление о включении в реестр НКО / Письмо-подтверждение о не включении'),
        ),
        migrations.AlterField(
            model_name='organizationregistrationrequest',
            name='state_registration_certificate',
            field=models.FileField(upload_to=apps.organizations.models.organization_request_document_upload_to, validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.common.file_validators.FileContentTypeValidator(('application/pdf',)), apps.common.file_validators.FileSizeValidator(26214400), apps.common.file_validators.FileSignatureValidator(b'%PDF', 'Uploaded file must be a valid PDF document.')], verbose_name='Свидетельство о гос регистрации ЮЛ / Свидетельство о регистрации НКО'),
        ),
        migrations.AlterField(
            model_name='organizationreportdocument',
            name='document',
            field=models.FileField(upload_to=apps.organizations.models.organization_report_document_upload_to, validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.common.file_validators.FileContentTypeValidator(('application/pdf',)), apps.common.file_validators.FileSizeValidator(26214400), apps.common.file_validators.FileSignatureValidator(b'%PDF', 'Uploaded file must be a valid PDF document.')]),
        ),
    ]
